
##Log
logging:
  level:
    sql: debug
    jdbc:
      sql-timing: debug
      resultsettable: off
      resultset: off
      audit: off
      result: off
      connection: off
      sqlonly: off
    org:
      springframework: info
      hibernate:
        SQL: off

#logging:
#  level:
#    com:
#      comfunny:
#        MyProject: debug
#    org:
#      springframework:
#        web: debug
#      hibernate:
#        SQL: off
#    sql: error
#    jdbc:
#      sqltiming: info
#      resultsettable: info
#      audit: off
#      resultset: off
#      connection: off
#      sqlonly: debug
#  file:
#    max-history: 9999999
#    max-size: 100MB
#    name: ${user.home}/logs/product.log
#  pattern:
#    console: %5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n
#    file: %5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n

